---

apiVersion: v1
kind: Namespace
metadata:
  name: upgrade-tool

---

apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: upgrade-tool
  name: controller

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: upgrade-tool-controller-cluster-admin
subjects:
- kind: ServiceAccount
  namespace: upgrade-tool
  name: controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: upgrade-tool-controller-privileged
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:privileged
subjects:
- kind: ServiceAccount
  namespace: upgrade-tool
  name: controller

---

apiVersion: v1
kind: Pod
metadata:
  namespace: upgrade-tool
  name: controller
  labels:
    app: controller
spec:
  serviceAccountName: controller
  containers:
  - name: controller
    image: quay.io/mlorenzofr/upgrade-tool:latest
    imagePullPolicy: IfNotPresent
    command:
    - /bin/upgrade-tool
    - start
    - controller
    - --mute=true
    - --log-file=stdout
    - --log-level=1
    - --namespace=upgrade-tool
